/* Generated by solo5-elftool version v0.6.4, do not edit */

#define MFT_ENTRIES 2
#include "mft_abi.h"

MFT1_NOTE_DECLARE_BEGIN
{
  .version = MFT_VERSION, .entries = 2,
  .e = {
    { .name = "", .type = MFT_RESERVED_FIRST },
    { .name = "service", .type = MFT_DEV_NET_BASIC },
  }
}
MFT1_NOTE_DECLARE_END
