* Background

In industry, there are multiple Serverless computing providers, for example, Amazon has AWS Lambda,
Microsoft has Azure Functions and Google provide Cloud Functions. Apache also have their own
serverles platform called Apache OpenWhisk. 
Since all of these provide the same fundamental FaaS service, it becomes apparent
that their architectural implementations are very similar and have a lot of common features.

The nature of Faas and the serverless computing paradigm means that a lot of similarities can be
drawn from all of the above providers. For example, due to the simplicity of a single Function, in
that it only performs a single/minimal action, it makes sense that they should be Event Driven where
some event will trigger the invokation of a function.
Continuing on from this, due to the typically asynchronous behaviour of individual functions, it is
common across all platforms that the receives an address where the final result of the function can
be stored, which means that functions themselves need to update a datastore to be useful. In
addition, all functions are ephemeral which means that they themselves do not store any local state
during execution, and if the client running the function fails for any reason, all of the work done
is lost and needs to be restarted.

Due to the scalability that needs to be provided in a Cloud Computing context, this Database needs
to able to scale well to store large amounts of data, and so they are typically some sort of NoSQL
database such as DynamoDB (Amazon), Firestore (Google), Cassandra, etc. 

To set up a function to be run, a configuration needs to be specified initially. The configuration
will say how much space the function will need, its expected runtime/timeout limit, the code size,
output size, parameters to functions, environement variable, etc.
This then by definition mean that fucntions are inherently immutable during runtime and the only way
to change what work is done is during the initial configuration/invokation of a function. This also
means that they offer no user interaction.

Functions need to provide a mapping between a single input, to a single output. That said, the
ability to update multiple data items can be provided by the use of different datastores such as
MongoDB which is a Document Database, a document in this case is defined to be a key-value pair,
where a value can be another set of key-value pairs.
